name: Minikube-Kubernetes Cluster interaction

on:
  workflow_dispatch:

jobs:
  laboratorio:
    name: Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: 'v1.24.0'
          kubernetes version: 'v1.23.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: |
          sleep 10
          kubectl get nodes
      - name: Install Helm
        uses: azure/setup-helm@v2
        with:
          version: "v3.8.2"
      - name: Deploy Chart fastapi
        working-directory: charts/fastapi
        run: |
          helm upgrade -i fastapi . --namespace default
      - name: Helm ls
        working-directory: charts/fastapi
        run: |
          sleep 20
          helm ls
